### ISSUE TITLE
Run code through ShellCheck

### ISSUE THREAD

**Issue by pkill37** [RJ-Jesus/Shell-Scripts#1]
Hi,

I found a useful tool that detects problems (syntax, POSIX compatibility, portability) with shell scripts and gives suggestions on how to fix them.

http://www.shellcheck.net/

I thought you might want to check it out and use it for your scripts. :smile:

**Comment by rj-jesus** [comment]
Thanks for the heads up. It does seem quite useful. Once I get some free time I'll look more into it, and might even rewrite one or another. Besides I have some others in development which I'll probably make public by then.

Once again, thanks for letting me know :smile:
Ricardo Jesus
